# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  encoding: unicode
  database: micro_reddit_development
  pool: 5
  username: micro_reddit
  password: password1

  
test:
  <<: *default
  encoding: unicode
  database: micro_reddit_test
  pool: 5
  username: micro_reddit
  password: password1

production:
  <<: *default
  database: micro_reddit_production
  username: micro_reddit
  password: <%= ENV["MICRO_REDDIT_DATABASE_PASSWORD"] %>
